apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb2:8086
    jsonData:
      version: Flux
      organization: docs
      defaultBucket: home
    secureJsonData:
      token: $INFLUX_TOKEN